version: '3.9'

services:
  db:
    image: postgres:alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db-casa-do-codigo
    ports:
      - "5432:5432"